service: student-enrollment-serverless

provider:
  name: aws
  runtime: python3.9
  region: us-east-1

plugins:
  - serverless-python-requirements

package:
  individually: true

custom:
  pythonRequirements:
    dockerizePip: non-linux

functions:
  enroll_student:
    handler: enroll_student.main.handler
    module: lambdas


